# Generated by Django 3.2.4 on 2022-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='match_date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='match',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('match', 'match_date')},
        ),
    ]
