# Generated by Django 3.2.4 on 2022-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('FixtureId', models.AutoField(primary_key=True, serialize=False)),
                ('HomeTeam', models.CharField(max_length=500)),
                ('AwayTeam', models.CharField(max_length=500)),
                ('MatchResult', models.CharField(max_length=500)),
                ('MatchDate', models.CharField(max_length=500)),
            ],
        ),
    ]
