# Generated by Django 3.2.4 on 2022-12-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TFFmedya', '0006_user_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportType', models.CharField(max_length=500)),
                ('ReportTitle', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=2000)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users2', to='TFFmedya.user')),
            ],
        ),
    ]
