# Generated by Django 3.2.4 on 2022-11-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['votes']},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Polls.question'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choice_text', 'question')},
        ),
    ]
