# Generated by Django 3.2.4 on 2022-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_auto_20221113_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
