# Generated by Django 3.2.4 on 2022-12-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_alter_question_question_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
