# Generated by Django 3.2.4 on 2022-12-31 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isPOTM',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
