# Generated by Django 4.1.2 on 2022-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerId', models.AutoField(primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=500)),
                ('Team', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamId', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=500)),
            ],
        ),
    ]
