# Generated by Django 3.2.4 on 2022-11-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
