# Generated by Django 3.2.4 on 2022-11-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
