# Generated by Django 3.2.4 on 2022-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
