# Generated by Django 3.2.4 on 2022-12-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0005_auto_20221119_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Point',
            field=models.IntegerField(default=0),
        ),
    ]
