# Generated by Django 3.2.4 on 2023-01-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0006_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
