# Generated by Django 3.2.4 on 2022-12-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0006_user_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Point',
        ),
    ]
