# Generated by Django 3.2.4 on 2022-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFFmedya', '0007_remove_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Point',
            field=models.IntegerField(default=0),
        ),
    ]
