# Generated by Django 3.2.4 on 2022-12-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('ref_link', models.CharField(max_length=250)),
            ],
        ),
    ]
